kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-volume-claim
  namespace: kafka
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Mi
